# Perceptron From Scratch

This practical demonstrates how a single artificial neuron works.

We implement a perceptron manually using:
- Inputs
- Weights
- Bias
- Weighted Sum
- Step Activation Function
- Prediction

In [3]:
%pip install numpy scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [4]:
# import libraries
import numpy as np

In [5]:
#STEP 2 — Create dataset
X = np.array([
    [1, 1],
    [1, 0],
    [0, 1],
    [0, 0]
])

y = np.array([1, 1, 0, 0])

In [6]:
# STEP 3 — Create weights
weights = np.array([0.5, 0.5])
# STEP 4 — Create bias
bias = -0.5

In [7]:
# STEP 5 — Weighted Sum
weighted_sum = np.dot(X, weights) + bias
print(weighted_sum)

[ 0.5  0.   0.  -0.5]


In [8]:
# STEP 6 — Step Activation Function
def step_function(z):
    return np.where(z >= 0, 1, 0)

In [9]:
# STEP 7 — Make predictions
y_pred = step_function(weighted_sum)

print(y_pred)

[1 1 1 0]


In [11]:
# step 8 — Print inputs, weights, bias, weighted sum, predictions, and actual values
print("Inputs:")
print(X)

print("\nWeights:")
print(weights)

print("\nBias:")
print(bias)

print("\nWeighted Sum:")
print(weighted_sum)

print("\nPredictions:")
print(y_pred)

print("\nActual:")
print(y)

Inputs:
[[1 1]
 [1 0]
 [0 1]
 [0 0]]

Weights:
[0.5 0.5]

Bias:
-0.5

Weighted Sum:
[ 0.5  0.   0.  -0.5]

Predictions:
[1 1 1 0]

Actual:
[1 1 0 0]
